version: '3'
services:
  redis:
    image: redis:latest
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: openecoe_1234
      MYSQL_DATABASE: openECOE_dev
      MYSQL_USER: openecoe
      MYSQL_PASSWORD: openecoe
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      retries: 3
  openecoe-api:
    build:
      context: .
      dockerfile: .docker/prod.dockerfile
    image: openecoe/api
    container_name: openecoe-api
    ports:
      - 8082:1080
    volumes:
      - .docker/deploy/local.env:/app/api/.env
    environment:
      SECRET_KEY: eiQuain4_aelohKa3_giGh6Fai_reeTh6Ai_Aegeic6l_ekuigo0M_aeph6Qua_uuZaac5n
      BCRYPT_LOG_ROUNDS: 4
      DEBUG: "True"
      TESTING: "False"
      LOG_TO_STDOUT: "True"
      SQLALCHEMY_TRACK_MODIFICATIONS: "False"
      API_AUTH: "True"
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://openecoe:openecoe@mysql/openECOE_dev
      CHRONO_ROUTE: http://localhost:8082
      EMAIL: ecoe@umh.es
      PASSWORD: Ki0uchee
      FIRSTNAME: Open
      SURNAME: ECOE
      ORGANIZATION: UMH
      RQ_REDIS_URL: 'redis://redis:6379/0'
      ALEMBIC_UPGRADE: DO
    depends_on:
      mysql:
          condition: service_healthy
      redis:
        condition: service_healthy

