version: '3'
services:
  redis:
    image: redis:latest
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: openecoe_1234
      MYSQL_DATABASE: openECOE_dev
      MYSQL_USER: openecoe
      MYSQL_PASSWORD: openecoe
    volumes:
      - ./.docker/data:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      retries: 3
  api:
    build:
      context: .
      dockerfile: .docker/prod.dockerfile
    image: openecoe/api
    ports:
      - 8000:1081
    environment:
      # API Configuration
      SERVER_NAME: localhost
      DEBUG: "True"
      TESTING: "False"
      BCRYPT_LOG_ROUNDS: 4
      SQLALCHEMY_TRACK_MODIFICATIONS: "False"
      API_AUTH: "True"
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://openecoe:openecoe@mysql/openECOE_dev
      RQ_REDIS_URL: 'redis://redis:6379/0'
      CHRONO_ROUTE: http://localhost:8082
      LOG_TO_STDOUT: "True"
      # Data for first run
      EMAIL: ecoe@umh.es
      PASSWORD: Ki0uchee
      FIRSTNAME: Open
      SURNAME: ECOE
      ORGANIZATION: UMH
      ALEMBIC_UPGRADE: DO
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy

