version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: openecoe_1234
      MYSQL_DATABASE: openECOE_dev
      MYSQL_USER: openecoe
      MYSQL_PASSWORD: openecoe