version: '3'
services:
  db:
    extends:
      file: .docker/docker-compose.persistence.yml
      service: db
  redis:
    extends:
      file: .docker/docker-compose.persistence.yml
      service: redis
  api:
    build: 
      context: .
      target: debug
    image: openecoe/api:debug
    volumes:
      - ./:/app/api
    ports:
      - 5000:5000
      - 5678:5678
    env_file:
      - ./environments/dev.env
    environment:
      # Data for first run if no organization created
      EMAIL: ecoe@umh.es
      PASSWORD: Ki0uchee
      FIRSTNAME: Open
      SURNAME: ECOE
      ORGANIZATION: UMH
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status/"]
      interval: 30s
      timeout: 10s
      retries: 3
  worker:
    build: 
      context: .
      target: debug
    image: openecoe/api:debug
    entrypoint: [ "flask", "rq", "worker"]
    volumes:
      - ./:/app/api
    env_file:
      - ./environments/dev.env
    depends_on:
      redis:
        condition: service_started

