version: '3'
services:
  api:
    build: 
      context: .
      target: debug
    image: openecoe/api:debug
    volumes:
      - ./:/app/api
    ports:
      - 5000:5000
      - 5678:5678
    env_file:
      - ./environments/dev.env
    environment:
      # Data for first run if no organization created
      EMAIL: ecoe@umh.es
      PASSWORD: Ki0uchee
      FIRSTNAME: Open
      SURNAME: ECOE
      ORGANIZATION: UMH
      ALEMBIC_UPGRADE: DO
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status/"]
      interval: 30s
      timeout: 10s
      retries: 3
  rq-worker:
    build: 
      context: .
      target: debug
    image: openecoe/api:debug
    entrypoint: [ "flask", "rq", "worker"]
    volumes:
      - ./:/app/api
    env_file:
      - ./environments/dev.env
    depends_on:
      redis:
        condition: service_started
  redis:
    image: redis:latest
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: openecoe_1234
      MYSQL_DATABASE: openECOE_dev
      MYSQL_USER: openecoe
      MYSQL_PASSWORD: openecoe
    volumes:
      - ./.docker/data:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      retries: 3

