version: '3'
services:
  api:
    build: 
      context: .
      target: debug
    image: openecoe/api:debug
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "openECOE-API",  "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]
    volumes:
      - ./:/app/api
    ports:
      - 5000:5000
      - 5678:5678
    env_file:
      - ./environments/dev.env
    environment:
      # Data for first run
      EMAIL: ecoe@umh.es
      PASSWORD: Ki0uchee
      FIRSTNAME: Open
      SURNAME: ECOE
      ORGANIZATION: UMH
      ALEMBIC_UPGRADE: DO
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_started
  redis:
    image: redis:latest
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: openecoe_1234
      MYSQL_DATABASE: openECOE_dev
      MYSQL_USER: openecoe
      MYSQL_PASSWORD: openecoe
    volumes:
      - ./.docker/data:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      retries: 3

