version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: openecoe_1234
      MYSQL_DATABASE: openECOE_dev
      MYSQL_USER: openecoe
      MYSQL_PASSWORD: openecoe
  api:
    image: openecoe/api:2022-06-29
    ports:
      - 8082:1080
    volumes:
      - ./deploy/local.env:/app/api/.env
