supervisor_unix_http_server_enable: true
#supervisor_unix_http_server_socket_path: /var/run/supervisord.sock
supervisor_unix_http_server_socket_path: /var/run/supervisord.sock

supervisor_programs:
  - name: '{{project_main_controller}}'
    command: "{{venv_path}}/bin/gunicorn -b localhost:8000 -w {{app_workers}} {{project_main_controller}}:app"
    state: present
    configuration: |
      directory={{project_path}}
      user=ubuntu
      autostart=true
      autorestart=true
      stopasgroup=true
      killasgroup=true
      stopsignal=INT
      environment = FLASK_APP="{{project_main_controller}}"