- name: Create .env configuration file
  template:
    src: env_template
    dest: "{{project_path}}/.env"
    mode: 0644

- name: Create virtualenv
  pip:
    virtualenv: "{{ venv_path }}"
    virtualenv_python: python3
    requirements: "{{ requirements_path }}"
  tags: virtualenv