- name: Include SSL certificates
  include_vars:
    file: certificate.yml
    name: certificate

- name: make sure SSL certificate is installed
  copy:
    content: "{{ certificate.ssl_certificate }}"
    dest: /home/vagrant/cert.pem
    owner: root
    group: root
    mode: 0644

- name: make sure SSL private key is installed
  copy:
    content: "{{ certificate.ssl_private_key }}"
    dest: /home/vagrant/key.pem
    owner: root
    group: root
    mode: 0600
  no_log: true

- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

- git:
    repo: "git@github.com:openECOE/openECOE-API.git"
    dest: "{{project_path}}"
    version: vagrant
    key_file: /home/vagrant/key.pem
    accept_hostkey: yes
    force: yes