---
# configure base dependencies
  - name: make sure nginx is installed
    apt:
      name: nginx
      state: present
      update_cache: yes
    when: env != "develop"

  - name: make sure Python 3 is installed
    apt:
      name: python3
      state: present
      update_cache: yes

  - name: make sure PIP is installed
    apt:
      name: python3-pip
      state: present
      update_cache: yes

  - name: make sure 'virtualenv' package is installed
    pip:
      name: virtualenv
      executable: pip3