- name: Install Python 3
  apt:
    name: python3
    state: present
    update_cache: yes

- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Install pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install 'virtualenv' package
  pip:
    name: virtualenv
    executable: pip3

- name: Create virtualenv
  become: no
  pip:
    virtualenv: "{{ venv_path }}"
    virtualenv_python: python3
    requirements: "{{ requirements_path }}"