"""empty message

Revision ID: 0c804508a5f5
Revises: 
Create Date: 2018-03-07 11:55:54.204390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c804508a5f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chro',
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_chronometer')
    )
    op.create_table('org',
    sa.Column('id_organization', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_organization')
    )
    op.create_table('perm',
    sa.Column('id_permission', sa.Integer(), nullable=False),
    sa.Column('id_typePermission', sa.Integer(), nullable=True),
    sa.Column('id_organization', sa.Integer(), nullable=True),
    sa.Column('id_ecoe', sa.Integer(), nullable=True),
    sa.Column('id_station', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_permission')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('ala',
    sa.Column('id_alarm', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('sound', sa.String(length=550), nullable=True),
    sa.Column('id_chronometer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chro.id_chronometer'], ),
    sa.PrimaryKeyConstraint('id_alarm')
    )
    op.create_table('ecoe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_organization', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_organization'], ['org.id_organization'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orguser',
    sa.Column('id_organization', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_organization'], ['org.id_organization'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_organization', 'id_user')
    )
    op.create_table('userperm',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_permission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permission'], ['perm.id_permission'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_permission')
    )
    op.create_table('area',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_ecoe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.PrimaryKeyConstraint('id_area')
    )
    op.create_table('day',
    sa.Column('id_day', sa.Integer(), nullable=False),
    sa.Column('id_ecoe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.PrimaryKeyConstraint('id_day')
    )
    op.create_table('ecoechro',
    sa.Column('id_ecoe', sa.Integer(), nullable=False),
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chro.id_chronometer'], ),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.PrimaryKeyConstraint('id_ecoe', 'id_chronometer')
    )
    op.create_table('sta',
    sa.Column('id_station', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_ecoe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.PrimaryKeyConstraint('id_station')
    )
    op.create_table('group',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_station', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_station'], ['sta.id_station'], ),
    sa.PrimaryKeyConstraint('id_group')
    )
    op.create_table('shi',
    sa.Column('id_shift', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('id_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_day'], ['day.id_day'], ),
    sa.PrimaryKeyConstraint('id_shift')
    )
    op.create_table('stachro',
    sa.Column('id_station', sa.Integer(), nullable=False),
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chro.id_chronometer'], ),
    sa.ForeignKeyConstraint(['id_station'], ['sta.id_station'], ),
    sa.PrimaryKeyConstraint('id_station', 'id_chronometer')
    )
    op.create_table('ques',
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('option_type', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['area.id_area'], ),
    sa.ForeignKeyConstraint(['id_group'], ['group.id_group'], ),
    sa.PrimaryKeyConstraint('id_question')
    )
    op.create_table('round',
    sa.Column('id_round', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id_shift', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_shift'], ['shi.id_shift'], ),
    sa.PrimaryKeyConstraint('id_round')
    )
    op.create_table('opt',
    sa.Column('id_option', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id_questions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_questions'], ['ques.id_question'], ),
    sa.PrimaryKeyConstraint('id_option')
    )
    op.create_table('stu',
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('dni', sa.String(length=25), nullable=True),
    sa.Column('id_ecoe', sa.Integer(), nullable=True),
    sa.Column('id_round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.ForeignKeyConstraint(['id_round'], ['round.id_round'], ),
    sa.PrimaryKeyConstraint('id_student')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stu')
    op.drop_table('opt')
    op.drop_table('round')
    op.drop_table('ques')
    op.drop_table('stachro')
    op.drop_table('shi')
    op.drop_table('group')
    op.drop_table('sta')
    op.drop_table('ecoechro')
    op.drop_table('day')
    op.drop_table('area')
    op.drop_table('userperm')
    op.drop_table('orguser')
    op.drop_table('ecoe')
    op.drop_table('ala')
    op.drop_table('user')
    op.drop_table('perm')
    op.drop_table('org')
    op.drop_table('chro')
    # ### end Alembic commands ###
