"""Allow decimal values in Option points

Revision ID: 1c0413e6c078
Revises: 3e9d62427b1e
Create Date: 2018-06-05 13:34:28.495259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0413e6c078'
down_revision = '3e9d62427b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('option', 'points',
                    existing_type=sa.Integer,
                    type_=sa.Numeric(10,2),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('option', 'points',
                    existing_type=sa.Numeric(10,2),
                    type_=sa.Integer,
                    existing_nullable=True)
    # ### end Alembic commands ###
