"""Add description to Area

Revision ID: 259c2b26d274
Revises: 68e16a8513a6
Create Date: 2025-11-25 10:39:30.861711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259c2b26d274'
down_revision = '68e16a8513a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('weith', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'weith')
    # ### end Alembic commands ###
