"""Jobs created date

Revision ID: 2a0ab16ad181
Revises: 8c47f42ec1d5
Create Date: 2020-03-27 12:25:07.201197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0ab16ad181'
down_revision = '8c47f42ec1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('job', sa.Column('finished', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'finished')
    op.drop_column('job', 'created')
    # ### end Alembic commands ###
