"""empty message

Revision ID: 2f369ba3803f
Revises: 01942fd243cf
Create Date: 2018-04-11 08:06:01.173610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f369ba3803f'
down_revision = '01942fd243cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecoe_chrono',
    sa.Column('id_ecoe', sa.Integer(), nullable=False),
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chronometer.id_chronometer'], ),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.PrimaryKeyConstraint('id_ecoe', 'id_chronometer')
    )
    op.create_table('ecoe_student',
    sa.Column('id_ecoe', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['student.id_student'], ),
    sa.PrimaryKeyConstraint('id_ecoe', 'id_student')
    )
    op.create_table('station_chrono',
    sa.Column('id_station', sa.Integer(), nullable=False),
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chronometer.id_chronometer'], ),
    sa.ForeignKeyConstraint(['id_station'], ['station.id_station'], ),
    sa.PrimaryKeyConstraint('id_station', 'id_chronometer')
    )
    op.drop_table('station_chronometer')
    op.drop_table('ecoechro')
    op.drop_table('ecoestu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecoestu',
    sa.Column('id_ecoe', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_student', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], name='ecoestu_ibfk_1'),
    sa.ForeignKeyConstraint(['id_student'], ['student.id_student'], name='ecoestu_ibfk_2'),
    sa.PrimaryKeyConstraint('id_ecoe', 'id_student'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ecoechro',
    sa.Column('id_ecoe', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_chronometer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chronometer.id_chronometer'], name='ecoechro_ibfk_1'),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], name='ecoechro_ibfk_2'),
    sa.PrimaryKeyConstraint('id_ecoe', 'id_chronometer'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('station_chronometer',
    sa.Column('id_station', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_chronometer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chronometer.id_chronometer'], name='station_chronometer_ibfk_1'),
    sa.ForeignKeyConstraint(['id_station'], ['station.id_station'], name='station_chronometer_ibfk_2'),
    sa.PrimaryKeyConstraint('id_station', 'id_chronometer'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('station_chrono')
    op.drop_table('ecoe_student')
    op.drop_table('ecoe_chrono')
    # ### end Alembic commands ###
