"""empty message

Revision ID: 30908d12d407
Revises: 2f369ba3803f
Create Date: 2018-04-11 11:05:52.395785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30908d12d407'
down_revision = '2f369ba3803f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
