"""Added RANGE_SELECT QuestionType

Revision ID: 332bcb12723c
Revises: be3a27c5c76b
Create Date: 2018-05-28 16:38:17.914830

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '332bcb12723c'
down_revision = 'aca54da4f713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question',
                    'question_type',
                    existing_type=sa.Enum('RADIO_BUTTON', 'CHECK_BOX', name='qtype'),
                    type_=sa.Enum('RADIO_BUTTON', 'CHECK_BOX', 'RANGE_SELECT', name='qtype')
                    )

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question',
                    'question_type',
                    type_=sa.Enum('RADIO_BUTTON', 'CHECK_BOX', name='qtype'),
                    existing_type=sa.Enum('RADIO_BUTTON', 'CHECK_BOX', 'RANGE_SELECT', name='qtype')
                    )
    # ### end Alembic commands ###
