"""ECOE Coordinator and Station Manager

Revision ID: 3b01a311dc3d
Revises: 80ffd2f2db51
Create Date: 2019-07-12 07:36:31.240380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b01a311dc3d'
down_revision = '80ffd2f2db51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoe', sa.Column('id_coordinator', sa.Integer(), nullable=False))
    # Default ecoe coordinator to user 1
    op.execute("UPDATE ecoe SET id_coordinator=1")
    op.create_foreign_key('fk_ecoe_coordinator_user', 'ecoe', 'user', ['id_coordinator'], ['id'])
    op.add_column('station', sa.Column('id_manager', sa.Integer(), nullable=False))
    # Default station manager to user 1
    op.execute("UPDATE station SET id_manager=1")
    op.create_foreign_key('fk_station_manager_user', 'station', 'user', ['id_manager'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_station_manager_user', 'station', type_='foreignkey')
    op.drop_column('station', 'id_manager')
    op.drop_constraint('fk_ecoe_coordinator_user', 'ecoe', type_='foreignkey')
    op.drop_column('ecoe', 'id_coordinator')
    # ### end Alembic commands ###
