"""ECOE add chrono token

Revision ID: 3be7c7f85afa
Revises: f5d686356dbe
Create Date: 2020-02-07 13:12:10.536896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be7c7f85afa'
down_revision = 'f5d686356dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoe', sa.Column('chrono_token', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecoe', 'chrono_token')
    # ### end Alembic commands ###
