"""Updated Question Reference max characters

Revision ID: 3e9d62427b1e
Revises: fe7ca68eea18
Create Date: 2018-06-05 10:51:04.354149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e9d62427b1e'
down_revision = 'fe7ca68eea18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question_type',
               existing_type=mysql.ENUM('RADIO_BUTTON', 'CHECK_BOX', 'RANGE_SELECT'),
               nullable=False)

    op.alter_column('question','reference',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question_type',
               existing_type=mysql.ENUM('RADIO_BUTTON', 'CHECK_BOX', 'RANGE_SELECT'),
               nullable=True)

    op.alter_column('question', 'reference',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=True)
    # ### end Alembic commands ###
