"""Questions JSON Format

Revision ID: 5126c6c1a838
Revises: 966e0a3b6e33
Create Date: 2020-03-04 13:35:07.398500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5126c6c1a838'
down_revision = '966e0a3b6e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_station', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_station'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('answer_schema', sa.JSON(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_question'], ['question.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_student', 'id_question', name='answer_student_question_uk')
    )
    op.drop_table('students_options')
    op.drop_table('qblock')
    op.drop_table('qblocks_questions')
    op.drop_table('option')
    op.alter_column('ecoe', 'status',
               existing_type=mysql.ENUM('ARCHIVED', 'DRAFT', 'PUBLISHED', collation='latin1_general_ci'),
               nullable=False)
    op.add_column('question', sa.Column('id_block', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('id_station', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('question_schema', sa.JSON(), nullable=False))
    op.alter_column('question', 'order',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'question', 'block', ['id_block'], ['id'])
    op.create_foreign_key(None, 'question', 'station', ['id_station'], ['id'])
    op.drop_column('question', 'question_type')
    op.drop_column('question', 'description')
    op.drop_column('question', 'reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('reference', mysql.VARCHAR(collation='latin1_general_ci', length=100), nullable=True))
    op.add_column('question', sa.Column('description', mysql.VARCHAR(collation='latin1_general_ci', length=500), nullable=True))
    op.add_column('question', sa.Column('question_type', mysql.ENUM('RADIO_BUTTON', 'CHECK_BOX', 'RANGE_SELECT', collation='latin1_general_ci'), nullable=False))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.alter_column('question', 'order',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('question', 'question_schema')
    op.drop_column('question', 'id_station')
    op.drop_column('question', 'id_block')
    op.alter_column('ecoe', 'status',
               existing_type=mysql.ENUM('ARCHIVED', 'DRAFT', 'PUBLISHED', collation='latin1_general_ci'),
               nullable=True)
    op.create_table('option',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('points', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('label', mysql.VARCHAR(collation='latin1_general_ci', length=255), nullable=True),
    sa.Column('id_question', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_question'], ['question.id'], name='option_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('qblocks_questions',
    sa.Column('qblock_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['qblock_id'], ['qblock.id'], name='qblocks_questions_ibfk_1'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='qblocks_questions_ibfk_2'),
    sa.PrimaryKeyConstraint('qblock_id', 'question_id'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('qblock',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='latin1_general_ci', length=300), nullable=True),
    sa.Column('id_station', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_station'], ['station.id'], name='qblock_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('students_options',
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('option_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], name='students_options_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='students_options_ibfk_2'),
    sa.PrimaryKeyConstraint('student_id', 'option_id'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('answer')
    op.drop_table('block')
    # ### end Alembic commands ###
