""" ECOE relationship with Stage

Revision ID: 6001ab40216c
Revises: 5126c6c1a838
Create Date: 2020-03-18 13:15:19.996999

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6001ab40216c'
down_revision = '5126c6c1a838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('id_ecoe', sa.Integer(), nullable=False))

    # ### assign every stage to ECOE
    stage = sa.table(
        'stage',
        sa.Column('id', sa.Integer()),
        sa.Column('id_ecoe', sa.Integer())
        # Other columns not needed for the data migration
    )

    schedule = sa.table(
        'schedule',
        sa.Column('id', sa.Integer()),
        sa.Column('id_stage', sa.Integer()),
        sa.Column('id_ecoe', sa.Integer())
    )

    op.execute(stage.update().values(
        id_ecoe=sa.select([sa.func.max(schedule.c.id_ecoe, type_=sa.Integer)]).where(schedule.c.id_stage == stage.c.id)
    ))

    op.create_foreign_key(None, 'stage', 'ecoe', ['id_ecoe'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage', type_='foreignkey')
    op.drop_column('stage', 'id_ecoe')
    # ### end Alembic commands ###
