"""Remove unique ECOE name constraint

Revision ID: 68e16a8513a6
Revises: 2feeb2157394
Create Date: 2024-07-08 11:29:52.450115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e16a8513a6'
down_revision = '2feeb2157394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='ecoe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'ecoe', ['name'], unique=False)
    # ### end Alembic commands ###
