"""Relationship Answer with Station

Revision ID: 6e365ec7cf27
Revises: 73fea1b7b24b
Create Date: 2020-04-22 11:11:24.702899

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import table, select

revision = '6e365ec7cf27'
down_revision = '73fea1b7b24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('id_station', sa.Integer(), nullable=False))

    answer = table(
        'answer',
        sa.Column('id', sa.Integer()),
        sa.Column('id_station', sa.Integer()),
        sa.Column('id_question', sa.Integer())
        # Other columns not needed for the data migration
    )

    question = table(
        'question',
        sa.Column('id', sa.Integer()),
        sa.Column('id_station', sa.Integer())
        # Other columns not needed for the data migration
    )

    op.execute(answer.update().values(
        id_station=select([question.c.id_station]).where(answer.c.id_question == question.c.id)
    ))

    op.drop_constraint('answer_ibfk_1', 'answer', type_='foreignkey')
    op.drop_constraint('answer_ibfk_2', 'answer', type_='foreignkey')
    op.drop_constraint('answer_student_question_uk', 'answer', type_='unique')

    op.create_foreign_key('answer_ibfk_1', 'answer', 'student', ['id_student'], ['id'])
    op.create_foreign_key('answer_ibfk_2', 'answer', 'question', ['id_question'], ['id'])
    op.create_foreign_key('fk_answer_station', 'answer', 'station', ['id_station'], ['id'])

    op.create_unique_constraint('answer_student_question_uk', 'answer', ['id_station', 'id_student', 'id_question'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_answer_station', 'answer', type_='foreignkey')
    op.drop_constraint('answer_ibfk_1', 'answer', type_='foreignkey')
    op.drop_constraint('answer_ibfk_2', 'answer', type_='foreignkey')
    op.drop_column('answer', 'id_station')

    op.drop_constraint('answer_student_question_uk', 'answer', type_='unique')

    op.create_foreign_key('answer_ibfk_1', 'answer', 'student', ['id_student'], ['id'])
    op.create_foreign_key('answer_ibfk_2', 'answer', 'question', ['id_question'], ['id'])
    op.create_unique_constraint('answer_student_question_uk', 'answer', ['id_student', 'id_question'])

    # ### end Alembic commands ###
