"""URI for file created by Job

Revision ID: 73fea1b7b24b
Revises: 2a0ab16ad181
Create Date: 2020-03-31 07:57:05.067964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fea1b7b24b'
down_revision = '2a0ab16ad181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('file', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'file')
    # ### end Alembic commands ###
