"""roles and permissions model

Revision ID: 80ffd2f2db51
Revises: cbdfed147f1f
Create Date: 2019-07-10 13:10:24.627308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80ffd2f2db51'
down_revision = 'cbdfed147f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_object', sa.Integer(), nullable=True),
    sa.Column('object', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'name', 'id_object', 'object', name='uq_permission_id_user_name_id_object_object')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.Enum('SUPERADMIN', 'ADMIN', 'USER', 'EVAL', 'STUDENT', name='roletype'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'name', name='uq_role_id_user_name')
    )
    op.alter_column('option', 'points',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###

    # Assign superadmin role to organizations with 'is_superadmin'
    op.execute("INSERT INTO role (id_user, name) SELECT id, 'superadmin' FROM user where is_superadmin = true")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('option', 'points',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###
