"""Campo id_job_csv en la tabla ECOE

Revision ID: 82a963a80fee
Revises: d724f6ade78a
Create Date: 2022-12-02 11:17:39.110490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a963a80fee'
down_revision = 'd724f6ade78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoe', sa.Column('id_job_csv', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'ecoe', 'job', ['id_job_csv'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ecoe', type_='foreignkey')
    op.drop_column('ecoe', 'id_job_csv')
    # ### end Alembic commands ###
