"""empty message

Revision ID: 8379a703d775
Revises: 64c014aad71a
Create Date: 2018-04-17 09:54:04.613309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8379a703d775'
down_revision = '64c014aad71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_user',
    sa.Column('id_organization', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_organization'], ['organization.id_organization'], name='organization_user_ibfk_1'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], name='organization_user_ibfk_2'),
    sa.PrimaryKeyConstraint('id_organization', 'id_user'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
