"""empty message

Revision ID: 8ba9e880b9d1
Revises: a3dda3104e61
Create Date: 2018-03-23 09:27:54.308160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba9e880b9d1'
down_revision = 'a3dda3104e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chro',
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_chronometer')
    )
    op.create_table('ala',
    sa.Column('id_alarm', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('sound', sa.String(length=550), nullable=False),
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chro.id_chronometer'], ),
    sa.PrimaryKeyConstraint('id_alarm')
    )
    op.create_table('day',
    sa.Column('id_day', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id_ecoe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.PrimaryKeyConstraint('id_day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day')
    op.drop_table('ala')
    op.drop_table('chro')
    # ### end Alembic commands ###
