"""Campo id_job_csv en tabla Organization

Revision ID: 9b6e8b64a582
Revises: 82a963a80fee
Create Date: 2022-12-02 14:21:24.127988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6e8b64a582'
down_revision = '82a963a80fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('id_job_csv', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'organization', 'job', ['id_job_csv'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'id_job_csv')
    # ### end Alembic commands ###
