"""empty message

Revision ID: a1d03ae92635
Revises: 
Create Date: 2018-04-27 11:27:50.548828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d03ae92635'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chronometer',
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_chronometer'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization',
    sa.Column('id_organization', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_organization')
    )
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_table('alarm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('sound', sa.String(length=550), nullable=False),
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chronometer.id_chronometer'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecoe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_organization', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_organization'], ['organization.id_organization'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('area',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=257), nullable=True),
    sa.Column('id_ecoe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.PrimaryKeyConstraint('id_area'),
    sa.UniqueConstraint('name')
    )
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id_ecoe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecoe_chrono',
    sa.Column('id_ecoe', sa.Integer(), nullable=False),
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chronometer.id_chronometer'], ),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.PrimaryKeyConstraint('id_ecoe', 'id_chronometer')
    )
    op.create_table('station',
    sa.Column('id_station', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_ecoe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.PrimaryKeyConstraint('id_station'),
    sa.UniqueConstraint('name')
    )
    op.create_table('group',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_station', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_station'], ['station.id_station'], ),
    sa.PrimaryKeyConstraint('id_group'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('id_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_day'], ['day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_chrono',
    sa.Column('id_station', sa.Integer(), nullable=False),
    sa.Column('id_chronometer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chronometer'], ['chronometer.id_chronometer'], ),
    sa.ForeignKeyConstraint(['id_station'], ['station.id_station'], ),
    sa.PrimaryKeyConstraint('id_station', 'id_chronometer')
    )
    op.create_table('question',
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(length=500), nullable=True),
    sa.Column('option_type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['area.id_area'], ),
    sa.ForeignKeyConstraint(['id_group'], ['group.id_group'], ),
    sa.PrimaryKeyConstraint('id_question')
    )
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id_shift', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_shift'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_question'], ['question.id_question'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dni', sa.String(length=25), nullable=False),
    sa.Column('id_ecoe', sa.Integer(), nullable=False),
    sa.Column('id_round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ecoe'], ['ecoe.id'], ),
    sa.ForeignKeyConstraint(['id_round'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_option', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_option'], ['option.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_option', 'id_student', name='_option_student_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('student')
    op.drop_table('option')
    op.drop_table('round')
    op.drop_table('question')
    op.drop_table('station_chrono')
    op.drop_table('shift')
    op.drop_table('group')
    op.drop_table('station')
    op.drop_table('ecoe_chrono')
    op.drop_table('day')
    op.drop_table('area')
    op.drop_table('ecoe')
    op.drop_table('alarm')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_table('organization')
    op.drop_table('chronometer')
    # ### end Alembic commands ###
