"""empty message

Revision ID: aca54da4f713
Revises: 0c121185c1fe
Create Date: 2018-05-19 22:32:34.820723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca54da4f713'
down_revision = '0c121185c1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'order')
    # ### end Alembic commands ###
