"""Increased Qblock name size to 300 characters

Revision ID: cbdfed147f1f
Revises: 1c0413e6c078
Create Date: 2019-06-03 17:23:36.126922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdfed147f1f'
down_revision = '1c0413e6c078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qblock', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.VARCHAR(length=300),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qblock', 'name',
                    existing_type=sa.VARCHAR(length=300),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=True)
    # ### end Alembic commands ###
