"""empty message

Revision ID: f3f2d8d3541b
Revises: 2798bb9a22f6
Create Date: 2018-04-20 08:00:52.094651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f2d8d3541b'
down_revision = '2798bb9a22f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'student', ['dni'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    # ### end Alembic commands ###
