"""Added status field to ECOE

Revision ID: f5d686356dbe
Revises: 3b01a311dc3d
Create Date: 2020-02-05 13:50:44.508539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d686356dbe'
down_revision = '3b01a311dc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoe', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='ecoestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecoe', 'status')
    # ### end Alembic commands ###
