"""empty message

Revision ID: fb0368220928
Revises: f3f2d8d3541b
Create Date: 2018-04-20 13:36:43.509778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb0368220928'
down_revision = 'f3f2d8d3541b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id_answer', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_option', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_option'], ['option.id_option'], ),
    sa.ForeignKeyConstraint(['id_question'], ['question.id_question'], ),
    sa.ForeignKeyConstraint(['id_student'], ['student.id_student'], ),
    sa.PrimaryKeyConstraint('id_answer')
    )
    op.alter_column('student', 'dni',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=25),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'dni',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=25),
               nullable=True)
    op.drop_table('answer')
    # ### end Alembic commands ###
