version: '3'
services:
  api:
    build: 
      context: ..
      target: prod
    image: openecoe/api:latest
    ports:
      - 1081:1081
    env_file:
      - ../environments/prod.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status/"]
      interval: 30s
      timeout: 10s
      retries: 3
  rq-worker:
    build: 
      context: ..
      target: prod
    image: openecoe/api:latest
    entrypoint: [ "flask", "rq", "worker"]
    env_file:
      - ../environments/prod.env
    depends_on:
      api:
        condition: service_healthy