version: '3'
services:
  db:
    extends:
      file: docker-compose.persistence.yml
      service: db
  redis:
    extends:
      file: docker-compose.persistence.yml
      service: redis
  api:
    build: 
      context: ..
      target: prod
    image: openecoe/api:latest
    ports:
      - 1081:1081
    environment:
      RQ_REDIS_URL: 'redis://redis:6379/0'
      LOG_TO_STDOUT: 'True'
      SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://openecoe:openecoe@db/openECOE_dev'
      EMAIL: ecoe@umh.es
      PASSWORD: Ki0uchee
      FIRSTNAME: Open
      SURNAME: ECOE
      ORGANIZATION: UMH
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1081/status/"]
      interval: 30s
      timeout: 10s
      retries: 3
  worker:
    build: 
      context: ..
      target: prod
    image: openecoe/api:latest
    entrypoint: [ "flask", "rq", "worker"]
    environment:
      RQ_REDIS_URL: 'redis://redis:6379/0'