- name: Install Python 3
  apt:
    name: python3
    state: present
    update_cache: yes

- name: Install pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install 'virtualenv' package
  pip:
    name: virtualenv
    executable: pip3

