project_name: openECOE-API
project_path: "{{base_path}}/{{project_name}}"

venv_path: "{{project_path}}/.venv"
requirements_path: "{{project_path}}/requirements.txt"

environment_config:
  FLASK_APP: "{{project_path}}/openECOE-API.py"

mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb

mysql_root_password: RmhL2MQHfq0Z36f5IUar
mysql_databases:
  - name: "{{database_name}}"
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: "{{database_user}}"
    host: "%"
    password: "{{database_password}}"
    priv: "{{database_name}}.*:ALL"