name: Crear PR desde develop a uat

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  create-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          title: 'Sync develop with uat'
          body: 'Automated PR to sync changes from develop to uat'
          branch: 'uat'