name: tests

on:
    push:
    pull_request:
    schedule:
        - cron: '15 10 * * 6'

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [ '3.9', '3.10' ]
        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}

            - name: Build project
              run: make

            - name: Run tests
              run: make test
